### ISSUE TITLE
the game was not rendering

### ISSUE THREAD

**Issue by twmht** [yanpanlau/DDPG-Keras-Torcs#10]
Hi,

the game was not rendering (the rendering stuck here).

Any suggestion to investigate this issue?
![_001](https://cloud.githubusercontent.com/assets/1567200/21987359/34ee72ee-dc3e-11e6-8170-c8dc47594754.png)

**Comment by zzlqwq** [comment]
Hello, I have the same problem with you. Have you solved it?
