### ISSUE TITLE
some problem with keras 2.0.3

### ISSUE THREAD

**Issue by airsimonhan** [yanpanlau/DDPG-Keras-Torcs#19]
Using TensorFlow backend.
Traceback (most recent call last):
  File "ddpg.py", line 10, in <module>
    from keras.engine.training import collect_trainable_weights
ImportError: cannot import name collect_trainable_weights

**Comment by airsimonhan** [comment]
I have solved this problem.

**Comment by yanpanlau** [comment]
My version is still in keras 1.0. I think you can comment out

**Comment by yanpanlau** [comment]
My version is still Keras 1.00. I think you can just comment out "keras.engine.training import collect_trainable_weights" and re-train again.
