### ISSUE TITLE
malloc():memory corruption

### ISSUE THREAD

**Issue by XiaoPengZong** [yanpanlau/DDPG-Keras-Torcs#27]
After train the network about 800 episode, error happend, it shows that Error in ' /usr/local/lib/torcs/torcs-bin': malloc(): memory corruption: 0x00007f9da0c6ff10.
And I test my parameters, find that the learning effect is not good,  what method can solve this memory problem ,so that I can continue train my network. Thanks!

**Comment by rohit-mehra** [comment]
@XiaoPengZong Did you find the solution to this issue? Can you please share it here.
