### ISSUE TITLE
collect_trainable_weights seems to be out of date

### ISSUE THREAD

**Issue by Primus-zhao** [yanpanlau/DDPG-Keras-Torcs#7]
Hi Lau,

Thanks for sharing your work! Quite nice!
I found that in keras1.1.2 version collect_trainable_weights func has been removed, and in fact this func is not used in  your src, why keep the line of importing this?

**Comment by huyong1109** [comment]
That is used in keras 1.1.0.

**Comment by arsenious** [comment]
Comment out the lines (I think 3 of them), it doesn't seem to affect the code at all

**Comment by yanpanlau** [comment]
Yes. It seems to me collect_trainable_weight is an old function in keras.
If you comment out and retrain the network everything will be fine



2017年3月6日 14:53 於 "arsenious" <notifications@github.com> 寫道：
